### ISSUE TITLE
Hex encoder formatting strange behavior

### ISSUE THREAD

**Issue by egnascimento** [eclipse/paho.mqtt-spy#10]
When I use Hex Encoder, it doesn't read properly some bytes. I looks like it doesn't read well bytes greater then 0x7F.

Please, refer to the screen below. I'm publishing 7e 7f 80 81 82. See the subscription result.
![2016-12-07 14_25_44-mqtt-spy](https://cloud.githubusercontent.com/assets/13719031/20976257/1e2725b2-bc89-11e6-8d57-5d25f12c00f4.png)

**Comment by kamilfb** [comment]
hi @egnascimento, could you confirm which version are you using and on what platform/os?

**Comment by egnascimento** [comment]
Latest stable 0.5.4. But I also noticed the same behavior on 0.6.x.

**Comment by kamilfb** [comment]
I can recreate this - will investigate further...

**Comment by kamilfb** [comment]
Hi. Could you try the new beta? 0.6.0 beta (build 56) - [Mirror HTTP Server](http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.6.0-beta-b56-jar-with-dependencies.jar)

**Comment by kamilfb** [comment]
I hope this has been resolved. Please report back if you have any issues.

**Comment by alieslam** [comment]
@kamilfb, 

Still beta version has the same problem. 
![mqtt-spy 0 6 0 beta build 52](https://cloud.githubusercontent.com/assets/8179651/23397601/e747760a-fda1-11e6-8544-8138640596eb.png)

**Comment by egnascimento** [comment]
Sorry for such a bit delay. I'm confirming the behavior is the same. I'm
attaching my test screenshot.


​

2017-02-28 7:46 GMT-03:00 Kamil Baczkowicz <notifications@github.com>:

**Comment by kamilfb** [comment]
@egnascimento @alieslam - it seems to work for me fine - set input as hex and subscription formatter to hex encoder - 
![screenshot at 2017-08-06 21-51-38](https://user-images.githubusercontent.com/8521600/29006951-9422cc40-7af1-11e7-9b7f-02046e8047a5.png)
I'm wondering whether it behaves differently on Windows and Linux...

**Comment by egnascimento** [comment]
I retested here and I confirm the following:
- Problems persists in beta 52 in both Linux and Windows;
- Problem *solved *in *beta 56* in both Linux and Windows;

=)

THANK YOU!

2017-08-06 17:55 GMT-03:00 Kamil Baczkowicz <notifications@github.com>:

**Comment by kamilfb** [comment]
@egnascimento - cool - thank you for confirming this!
